### ISSUE TITLE
switch to new metadata system when it's actually documented / not "unworkable"

### ISSUE THREAD

**Issue by glyph** [glyph/QuickMacHotKey#1]
There's a deprecation warning that comes with using bridgesupport files, but there's no documentation of what to do instead.  https://github.com/ronaldoussoren/objective.metadata says that the tool is "unworkable" without some major changes.

cc @ronaldoussoren please let me know when there's a thing to do here :)

**Comment by ronaldoussoren** [comment]
Some day I'll finish the new tooling...  The tooling I'm using now is not on GitHub, requires Python 2.7 and has dependencies on my personal laptop :-(. 

Manual bindings might be more useful here though instead of using a bridgesupport file or my tooling. I'm traveling this week, with some luck I can create PR when I return.

**Comment by glyph** [comment]
Hey @ronaldoussoren 

> Manual bindings might be more useful here though instead of using a bridgesupport file or my tooling. I'm traveling this week, with some luck I can create PR when I return.

No pressure, I do not take "maybe I can make a PR" as a commitment, just bumping this since the library is starting to get a bit of attention and I'd love to understand what the clean "right" way to do this will be going forward.
